### ISSUE TITLE
uhttpd server runs in the background - How ?

### ISSUE THREAD

**Issue by bmsleight** [fadushin/esp8266#6]
Love this code.  

I think this is a silly question.... I have uhttpd running via Frozen Bytecode. Re: "Once started, the uhttpd server runs in the background, so that the ESP8266 can do other task"

When I run the Basic Usage example; server.run()
I can not see how uhttpd server runs in the background. I am missing something obvious ?

**Comment by fadushin** [comment]
Sorry, the docs are wrong.  There was a time you could do this, but since we moved to asyncio, we cannot (or I have not investigated the time to seeing if we can).  I'll fix the docs.
